export const ATTRIBUTE_NAMES = {
  ID: 'w-id',
  WIDGET_TYPE: 'w-type',
  DEFAULT_VALUE: 'data-default-value',

  TITLE_COLOR: 'w-titleColor',
  TITLE_HOVER_COLOR: 'w-titleHoverColor',
  ARROW_COLOR: 'w-arrowColor',
  ARROW_HOVER_COLOR: 'w-arrowHoverColor',
  EVENT_DATE_COLOR: 'w-dateColor',
  EVENT_DESCRIPTION_COLOR: 'w-descriptionColor',
  EVENTS_COUNTER_COLOR: 'w-counterColor',
};

export const CUSTOM_THEME_ATTRIBUTES = [
  ATTRIBUTE_NAMES.TITLE_COLOR,
  ATTRIBUTE_NAMES.TITLE_HOVER_COLOR,
  ATTRIBUTE_NAMES.ARROW_COLOR,
  ATTRIBUTE_NAMES.ARROW_HOVER_COLOR,
  ATTRIBUTE_NAMES.EVENT_DATE_COLOR,
  ATTRIBUTE_NAMES.EVENT_DESCRIPTION_COLOR,
  ATTRIBUTE_NAMES.EVENTS_COUNTER_COLOR,
];
